// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Faq': string;
  'active': string;
  'chevron': string;
  'chevron_icon': string;
  'item': string;
  'title': string;
  'topic': string;
  'topic_description': string;
  'topic_title': string;
}
export const cssExports: CssExports;
export default cssExports;
