// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Footer': string;
  'buyNft': string;
  'design': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
