// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Home': string;
  'button_buy': string;
  'button_container': string;
  'button_help': string;
  'home_descriptin': string;
  'home_title': string;
  'image_witch': string;
  'title_container': string;
}
export const cssExports: CssExports;
export default cssExports;
