// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'Header_navbar': string;
  'link': string;
  'link_waraper': string;
  'logo': string;
  'singIn': string;
  'singInIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
