// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Roadmap': string;
  'Roadmap_table': string;
  'about_description': string;
  'about_title': string;
  'elipce_blue': string;
  'elipce_container': string;
  'elipce_yellow': string;
  'title_container': string;
}
export const cssExports: CssExports;
export default cssExports;
