// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Collection': string;
  'collection_container': string;
  'collection_description': string;
  'collection_title': string;
  'contact': string;
  'contact_container': string;
  'description': string;
  'item': string;
  'nft': string;
  'text_container': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
