// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mint': string;
  'add_action': string;
  'add_field': string;
  'common_field': string;
  'field_title': string;
  'main': string;
  'mint_button': string;
  'topic': string;
  'topic_description': string;
  'topic_title': string;
  'total_field': string;
}
export const cssExports: CssExports;
export default cssExports;
